export const sportKinds = [
    "road-cycling",
    "mtb-cycling",
    "gravel-cycling",
    "canoeing",
    "bobsleigh",
    "swimming",
    "running",
    "hiking",
    "rowing",
    "alpine-skiing",
    "cross-country-skiing",
    "snowboarding",
    "luge",
    "triathlon",
    "motorsports",
] as const;
