name: Prod.Build-Deploy-Artifact

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: oven-sh/setup-bun@v1
            - uses: actions/cache@v3
              with:
                  path: |
                      ~./npm
                      ${{ github.workspace }}/panel/.next/cache
                      **/node_modules
                      ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
                  restore-keys: |
                      ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}-

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Build utils
              run: |
                  cd ./utils
                  bun run build

            - name: Build timer
              run: |
                  cd ./timer
                  bun run build

            - name: Generate prisma
              run: |
                  cd ./panel
                  bun run generate-prisma

            - name: Build panel
              run: |
                  cd ./panel
                  bun next telemetry disable
                  bun run build
                  rm -rf .next/cache

            - name: Bundle ZIP package
              uses: montudor/action-zip@v1
              with:
                  args: zip -qq --symlinks -r set-package.zip package.json bun.lockb panel utils timer

            - uses: actions/upload-artifact@v3
              with:
                name: application-artifact
                path: set-package.zip