name: Prod.Build_Lint

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    # Artifact build
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: oven-sh/setup-bun@v1
            - uses: actions/cache@v3
              with:
                  path: |
                      ~./npm
                      ${{ github.workspace }}/panel/.next/cache
                      **/node_modules
                      ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-app-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
                  restore-keys: |
                      ${{ runner.os }}-app-${{ hashFiles('**/bun.lockb') }}-

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Build library - utils
              run: |
                  cd ./utils
                  bun run build

            - name: Build library - timer
              run: |
                  cd ./timer
                  bun run build

            - name: Generate prisma
              run: |
                  cd ./panel
                  ls -la
                  bun run generate-prisma

            - name: Build Application
              run: |
                  cd ./panel
                  bun next telemetry disable
                  bun run build

            - name: Bundle Application Package
              uses: montudor/action-zip@v1
              with:
                  args: zip -qq --symlinks -r set-package.zip package.json bun.lockb panel utils timer -x "**/.next/cache/**"

            - uses: actions/upload-artifact@v3
              name: Store Application Package
              with:
                  name: application-artifact
                  path: set-package.zip

    # Code linting 
    # lint:
    #     runs-on: ubuntu-latest

    #     steps:
    #         - uses: actions/checkout@v3
    #         - uses: oven-sh/setup-bun@v1
    #         - uses: actions/cache@v3
    #           with:
    #               path: |
    #                   ~./npm
    #                   **/node_modules
    #               key: ${{ runner.os }}-lint-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
    #               restore-keys: |
    #                   ${{ runner.os }}-lint-${{ hashFiles('**/bun.lockb') }}-

    #         - name: Install dependencies
    #           run: bun install

    #         - name: Build library - utils
    #           run: |
    #               cd ./utils
    #               bun run build

    #         - name: Build library - timer
    #           run: |
    #               cd ./timer
    #               bun run build

    #         - name: Generate prisma
    #           run: |
    #               cd ./panel
    #               bun run generate-prisma

    #         - name: Lint
    #           run: |
    #               bun run lint
