name: Prod/delivery

on:
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Download Application Package
              uses: dawidd6/action-download-artifact@v2
              with:
                  workflow: build-lint.yml
                  workflow_conclusion: success

            - name: Upload Artifact
              uses: appleboy/scp-action@master
              with:
                  source: "application-artifact/"
                  host: ${{ secrets.OVH_REMOTE_HOST }}
                  username: ${{ secrets.OVH_REMOTE_USER }}
                  password: ${{ secrets.OVH_REMOTE_USER_PASSWORD }}
                  target: ${{ secrets.OVH_REMOTE_TARGET }}

            - name: Publish Artifact
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.OVH_REMOTE_HOST }}
                  username: ${{ secrets.OVH_REMOTE_USER }}
                  password: ${{ secrets.OVH_REMOTE_USER_PASSWORD }}
                  script: |
                      export NVM_DIR=~/.nvm
                      source ~/.nvm/nvm.sh
                      export BUN_INSTALL="$HOME/.bun"
                      export PATH=$BUN_INSTALL/bin:$PATH
                      echo $PATH
                      cd ${{ secrets.OVH_REMOTE_TARGET }}
                      mv application-artifact/set-package.zip set-package.zip
                      cp panel/server/prisma/database.db ../rura-databases/database-`date +"%Y%m%d%H%M"`.db
                      rm -rf node_modules/ application-artifact/ package/ package.json panel/ timer/ utils/ bun.lockb yarn.lock .yarnrc.yml
                      unzip -q set-package.zip
                      rm set-package.zip
                      cp ../app.rura.cc.env panel/.env
                      bun install
                      cd panel
                      cp `ls -dtr1 ../../rura-databases/* | tail -1` "server/prisma/database.db"
                      bun prisma generate
                      bun prisma migrate deploy
                      chmod -R 777 server/prisma
                      pm2 restart app.rura.cc/app
                      pm2 restart app.rura.cc/api
