name: Prod/integration

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    # Artifact build
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
            - uses: actions/cache@v4
              with:
                  path: |
                      ~./npm
                      **/.next/cache
                      **/node_modules
                  key: ${{ runner.os }}-app-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
                  restore-keys: |
                      ${{ runner.os }}-app-${{ hashFiles('**/bun.lockb') }}-

            - name: Install dependencies
              run: bun install

            - name: Build library - utils
              run: |
                  cd ./packages/utils
                  bun run build

            - name: Build library - timer
              run: |
                  cd ./packages/timer
                  bun run build

            - name: Generate prisma
              run: |
                  cd ./packages/panel
                  bun run generate-prisma

            - name: Build Application
              env:
                  NEXT_PUBLIC_NODE_ENV: ${{ secrets.NEXT_PUBLIC_NODE_ENV }}
                  NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
                  NEXT_PUBLIC_APP_PORT: ${{ secrets.NEXT_PUBLIC_APP_PORT }}
                  NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
              run: |
                  cd ./packages/panel
                  bun next telemetry disable
                  bun run build

            - name: Bundle Application Package
              uses: montudor/action-zip@v1
              with:
                  args: zip -qq --symlinks -r set-package.zip package.json bun.lockb packages -x "**/.next/cache/**"

            - uses: actions/upload-artifact@v4
              name: Store Application Package
              with:
                  name: application-artifact
                  path: set-package.zip

    # Code linting
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
            - uses: actions/cache@v4
              with:
                  path: |
                      ~./npm
                      **/node_modules
                  key: ${{ runner.os }}-lint-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
                  restore-keys: |
                      ${{ runner.os }}-lint-${{ hashFiles('**/bun.lockb') }}-

            - name: Install dependencies
              run: bun install

            - name: Build library - utils
              run: |
                  cd ./packages/utils
                  bun run build

            - name: Build library - timer
              run: |
                  cd ./packages/timer
                  bun run build

            - name: Generate prisma
              run: |
                  cd ./packages/panel
                  bun run generate-prisma

            - name: Lint
              run: |
                  bun run lint

    # Tests
    tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
            - uses: actions/cache@v4
              with:
                  path: |
                      ~./npm
                      **/node_modules
                  key: ${{ runner.os }}-lint-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
                  restore-keys: |
                      ${{ runner.os }}-lint-${{ hashFiles('**/bun.lockb') }}-

            - name: Install dependencies
              run: bun install

            - name: Build library - utils
              run: |
                  cd ./packages/utils
                  bun run build

            - name: Run tests
              run: |
                  cd ./packages/panel
                  bun run test

            - name: Run tests
              run: |
                  cd ./packages/timer
                  bun run test
