# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app - set-hub

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:

    build_timer:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: c-hive/gha-yarn-cache@v1

            - name: Set up Node.js version
                uses: actions/setup-node@v2-beta
                with:
                    node-version: "12.x"

            - name: npm install, build, and test
                run: |
                    cd ./timer
                    yarn install
                    yarn run build

            - uses: actions/upload-artifact@v2
            with:
                name: timer.dist
                path: ./timer

    build_hub:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: c-hive/gha-yarn-cache@v1

            - name: Set up Node.js version
                uses: actions/setup-node@v2-beta
                with:
                    node-version: "12.x"

            - name: npm install, build, and test
                run: |
                    cd ./hub
                    yarn install
                    yarn run build

            - uses: actions/upload-artifact@v2
            with:
                name: hub.dist
                path: ./hub

    build_results:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: c-hive/gha-yarn-cache@v1

            - name: Set up Node.js version
                uses: actions/setup-node@v2-beta
                with:
                    node-version: "12.x"

            - name: npm install, build, and test
                run: |
                    cd ./results
                    yarn install
                    yarn run build

            - uses: actions/upload-artifact@v2
            with:
                name: results.dist
                path: ./results

    build_mobile:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: c-hive/gha-yarn-cache@v1

            - name: Set up Node.js version
                uses: actions/setup-node@v2-beta
                with:
                    node-version: "12.x"

            - name: npm install, build, and test
                run: |
                    cd ./mobile
                    yarn install
                    yarn run build

            - uses: actions/upload-artifact@v2
            with:
                name: mobile.dist
                path: ./mobile

    build_server:
        needs: [build_timer, build_hub, build_results, build_mobile]
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/download-artifact@v2
                with:
                    name: build_timer
                    path: ./timer

            - uses: actions/download-artifact@v2
                with:
                    name: build_hub
                    path: ./hub

            - uses: actions/download-artifact@v2
                with:
                    name: build_results
                    path: ./results/dist

            - uses: actions/download-artifact@v2
                with:
                    name: build_mobile
                    path: ./mobile/dist

            - uses: c-hive/gha-yarn-cache@v1

            - name: Set up Node.js version
              uses: actions/setup-node@v2-beta
              with:
                  node-version: "12.x"

            - name: npm install, build, and test
              run: |
                  cd ./timer
                  yarn install
                  yarn run build
                  cd ../hub
                  yarn install
                  yarn run build
                  cd ../results
                  yarn install
                  yarn run build
                  cd ../mobile
                  yarn install
                  yarn run build
                  cd ../server
                  yarn install
                  yarn run build

            - uses: montudor/action-zip@v1
              with:
                  args: zip -qq -r set-hub-package.zip hub results timer server node_modules

            - run: |
                  mkdir package
                  mv set-hub-package.zip package/set-hub-package.zip

            - name: upload artifact to staging
              uses: SamKirkland/FTP-Deploy-Action@4.0.0
              with:
                  server: ${{ secrets.ftp_server }}
                  username: ${{ secrets.ftp_username }}
                  password: ${{ secrets.ftp_password }}
                  local-dir: ./package/
                  server-dir: domains/artifacts/

    deploy:
        runs-on: ubuntu-latest
        needs: build
        # environment:
        #     name: "production"
        # url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
            - name: publish
              uses: garygrossgarten/github-action-ssh@release
              with:
                  host: ${{ secrets.ssh_host }}
                  username: ${{ secrets.ssh_username }}
                  password: ${{ secrets.ssh_password }}
                  tryKeyboard: true
                  command: |
                      cd domains/set-hub.pyszstudio.pl/
                      rm -rf node_modules
                      rm -rf public_nodejs
                      unzip -q ../artifacts/set-hub-package.zip
                      mv server public_nodejs
                      devil www restart set-hub.pyszstudio.pl
