name: Prod.Publish

on:
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Download Application Package
              uses: dawidd6/action-download-artifact@v2
              with:
                  workflow: build-artifact.yml
                  workflow_conclusion: success

            - name: Upload Artifact
              uses: appleboy/scp-action@master
              with:
                  SOURCE: "application-artifact/"
                  HOST: ${{ secrets.OVH_REMOTE_HOST }}
                  USERNAME: ${{ secrets.OVH_REMOTE_USER }}
                  PASSWORD: ${{ secrets.OVH_REMOTE_USER_PASSWORD }}
                  TARGET: ${{ secrets.OVH_REMOTE_TARGET }}

            - name: Publish Artifact
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.OVH_REMOTE_HOST }}
                  username: ${{ secrets.OVH_REMOTE_USER }}
                  password: ${{ secrets.OVH_REMOTE_USER_PASSWORD }}
                  script: |
                      curl -fsSL https://bun.sh/install | bash 
                      source /home/ubuntu/.bashrc
                      export NVM_DIR=~/.nvm
                      source ~/.nvm/nvm.sh
                      cd ${{ secrets.OVH_REMOTE_TARGET }}
                      mv application-artifact/set-package.zip set-package.zip
                      cp panel/server/prisma/database.db ../rura-databases/database-`date +"%Y%m%d%H%M"`.db
                      rm -rf node_modules/ application-artifact/ package.json panel/ timer/ utils/ yarn.lock .yarnrc.yml
                      unzip -q set-package.zip
                      rm set-package.zip
                      cp ../app.rura.cc.env panel/.env
                      bun install --frozen-lockfile
                      cd panel
                      cp `ls -dtr1 ../../rura-databases/* | tail -1` "server/prisma/database.db"
                      bun prisma generate
                      bun prisma migrate deploy
                      chmod -R 777 server/prisma
                      pm2 restart app.rura.cc
