name: Build.Deploy

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: |
                      **/node_modules
                      ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Set up Node.js version
              uses: actions/setup-node@v2-beta
              with:
                  node-version: "16.x"

            - name: Install dependencies
              run: yarn install

            - name: Build shared
              run: |
                  cd ./shared
                  yarn build

            - name: Build timer
              run: |
                  cd ./timer
                  yarn build

            - name: Build panel
              run: |
                  cd ./panel
                  yarn build

            - name: Build server
              run: |
                  cd ./server
                  yarn build

            - name: Bundle ZIP package
              uses: montudor/action-zip@v1
              with:
                  args: zip -qq -r set-hub-package.zip panel shared timer server node_modules

            - run: |
                  mkdir package
                  mv set-hub-package.zip package/set-hub-package.zip

            - name: Upload artifact
              uses: easingthemes/ssh-deploy@main
              with:
                  TARGET: ${{ secrets.OVH_REMOTE_TARGET }}
                  ARGS: "-rltgoDzvO --delete"
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.OVH_SSH_PRIVATE_KEY }}
                  ARGS: "-rltgoDzvO --delete"
                  SOURCE: "package/"
                  REMOTE_HOST: ${{ secrets.OVH_REMOTE_HOST }}
                  REMOTE_USER: ${{ secrets.OVH_REMOTE_USER }}

    publish:
        needs: [build]
        runs-on: ubuntu-latest

        steps:
          - name: Publish
            uses: appleboy/ssh-action@master
            with:
                host: ${{ secrets.OVH_REMOTE_HOST }}
                username: ${{ secrets.OVH_REMOTE_USER }}
                key: ${{ secrets.OVH_SSH_PRIVATE_KEY }}
                script: |
                    cd ${{ secrets.OVH_REMOTE_TARGET }}
                    unzip -q set-hub-package.zip
                    cd server
                    yarn prisma db push
                    yarn prisma db seed